// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conditions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteConditionEntries = `-- name: DeleteConditionEntries :exec
DELETE FROM condition_entries
WHERE condition_name = ? AND source = ?
`

type DeleteConditionEntriesParams struct {
	ConditionName string `json:"condition_name"`
	Source        string `json:"source"`
}

func (q *Queries) DeleteConditionEntries(ctx context.Context, arg DeleteConditionEntriesParams) error {
	_, err := q.db.ExecContext(ctx, deleteConditionEntries, arg.ConditionName, arg.Source)
	return err
}

const getCondition = `-- name: GetCondition :one
SELECT name, source, page, srd, basic_rules FROM conditions WHERE name = ? AND source = ?
`

type GetConditionParams struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

func (q *Queries) GetCondition(ctx context.Context, arg GetConditionParams) (Condition, error) {
	row := q.db.QueryRowContext(ctx, getCondition, arg.Name, arg.Source)
	var i Condition
	err := row.Scan(
		&i.Name,
		&i.Source,
		&i.Page,
		&i.Srd,
		&i.BasicRules,
	)
	return i, err
}

const getConditionEntries = `-- name: GetConditionEntries :many
SELECT condition_name, source, ord, block_type, heading, content FROM condition_entries WHERE condition_name = ? AND source = ? ORDER BY ord
`

type GetConditionEntriesParams struct {
	ConditionName string `json:"condition_name"`
	Source        string `json:"source"`
}

func (q *Queries) GetConditionEntries(ctx context.Context, arg GetConditionEntriesParams) ([]ConditionEntry, error) {
	rows, err := q.db.QueryContext(ctx, getConditionEntries, arg.ConditionName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConditionEntry
	for rows.Next() {
		var i ConditionEntry
		if err := rows.Scan(
			&i.ConditionName,
			&i.Source,
			&i.Ord,
			&i.BlockType,
			&i.Heading,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertConditionEntry = `-- name: InsertConditionEntry :exec
INSERT INTO condition_entries (condition_name, source, ord, block_type, heading, content)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertConditionEntryParams struct {
	ConditionName string         `json:"condition_name"`
	Source        string         `json:"source"`
	Ord           int64          `json:"ord"`
	BlockType     string         `json:"block_type"`
	Heading       sql.NullString `json:"heading"`
	Content       string         `json:"content"`
}

func (q *Queries) InsertConditionEntry(ctx context.Context, arg InsertConditionEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertConditionEntry,
		arg.ConditionName,
		arg.Source,
		arg.Ord,
		arg.BlockType,
		arg.Heading,
		arg.Content,
	)
	return err
}

const upsertCondition = `-- name: UpsertCondition :exec
INSERT INTO conditions (name, source, page, srd, basic_rules)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name, source) DO UPDATE SET
    page = excluded.page,
    srd = excluded.srd,
    basic_rules = excluded.basic_rules
`

type UpsertConditionParams struct {
	Name       string        `json:"name"`
	Source     string        `json:"source"`
	Page       sql.NullInt64 `json:"page"`
	Srd        sql.NullInt64 `json:"srd"`
	BasicRules sql.NullInt64 `json:"basic_rules"`
}

func (q *Queries) UpsertCondition(ctx context.Context, arg UpsertConditionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCondition,
		arg.Name,
		arg.Source,
		arg.Page,
		arg.Srd,
		arg.BasicRules,
	)
	return err
}
