// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conditions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteConditionEntries = `-- name: DeleteConditionEntries :exec
DELETE FROM condition_entries
WHERE condition_name = ? AND source = ?
`

type DeleteConditionEntriesParams struct {
	ConditionName string `json:"condition_name"`
	Source        string `json:"source"`
}

func (q *Queries) DeleteConditionEntries(ctx context.Context, arg DeleteConditionEntriesParams) error {
	_, err := q.db.ExecContext(ctx, deleteConditionEntries, arg.ConditionName, arg.Source)
	return err
}

const insertConditionEntry = `-- name: InsertConditionEntry :exec
INSERT INTO condition_entries (condition_name, source, ord, block_type, heading, content)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertConditionEntryParams struct {
	ConditionName string         `json:"condition_name"`
	Source        string         `json:"source"`
	Ord           int64          `json:"ord"`
	BlockType     string         `json:"block_type"`
	Heading       sql.NullString `json:"heading"`
	Content       string         `json:"content"`
}

func (q *Queries) InsertConditionEntry(ctx context.Context, arg InsertConditionEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertConditionEntry,
		arg.ConditionName,
		arg.Source,
		arg.Ord,
		arg.BlockType,
		arg.Heading,
		arg.Content,
	)
	return err
}

const upsertCondition = `-- name: UpsertCondition :exec
INSERT INTO conditions (name, source, page, srd, basic_rules)
VALUES (?, ?, ?, ?, ?)
ON CONFLICT(name, source) DO UPDATE SET
    page = excluded.page,
    srd = excluded.srd,
    basic_rules = excluded.basic_rules
`

type UpsertConditionParams struct {
	Name       string        `json:"name"`
	Source     string        `json:"source"`
	Page       sql.NullInt64 `json:"page"`
	Srd        sql.NullInt64 `json:"srd"`
	BasicRules sql.NullInt64 `json:"basic_rules"`
}

func (q *Queries) UpsertCondition(ctx context.Context, arg UpsertConditionParams) error {
	_, err := q.db.ExecContext(ctx, upsertCondition,
		arg.Name,
		arg.Source,
		arg.Page,
		arg.Srd,
		arg.BasicRules,
	)
	return err
}
