// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: languages.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteLanguageScriptFonts = `-- name: DeleteLanguageScriptFonts :exec
DELETE FROM language_script_fonts
WHERE script_name = ? AND source = ?
`

type DeleteLanguageScriptFontsParams struct {
	ScriptName string `json:"script_name"`
	Source     string `json:"source"`
}

func (q *Queries) DeleteLanguageScriptFonts(ctx context.Context, arg DeleteLanguageScriptFontsParams) error {
	_, err := q.db.ExecContext(ctx, deleteLanguageScriptFonts, arg.ScriptName, arg.Source)
	return err
}

const deleteLanguageSpeakers = `-- name: DeleteLanguageSpeakers :exec
DELETE FROM language_typical_speakers
WHERE language_name = ? AND source = ?
`

type DeleteLanguageSpeakersParams struct {
	LanguageName string `json:"language_name"`
	Source       string `json:"source"`
}

func (q *Queries) DeleteLanguageSpeakers(ctx context.Context, arg DeleteLanguageSpeakersParams) error {
	_, err := q.db.ExecContext(ctx, deleteLanguageSpeakers, arg.LanguageName, arg.Source)
	return err
}

const getLanguage = `-- name: GetLanguage :one
SELECT name, source, page, type, script, srd, basic_rules FROM languages WHERE name = ? AND source = ?
`

type GetLanguageParams struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

func (q *Queries) GetLanguage(ctx context.Context, arg GetLanguageParams) (Language, error) {
	row := q.db.QueryRowContext(ctx, getLanguage, arg.Name, arg.Source)
	var i Language
	err := row.Scan(
		&i.Name,
		&i.Source,
		&i.Page,
		&i.Type,
		&i.Script,
		&i.Srd,
		&i.BasicRules,
	)
	return i, err
}

const getLanguageScript = `-- name: GetLanguageScript :one
SELECT name, source FROM language_scripts WHERE name = ? AND source = ?
`

type GetLanguageScriptParams struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

func (q *Queries) GetLanguageScript(ctx context.Context, arg GetLanguageScriptParams) (LanguageScript, error) {
	row := q.db.QueryRowContext(ctx, getLanguageScript, arg.Name, arg.Source)
	var i LanguageScript
	err := row.Scan(&i.Name, &i.Source)
	return i, err
}

const getLanguageScriptFonts = `-- name: GetLanguageScriptFonts :many
SELECT font FROM language_script_fonts WHERE script_name = ? AND source = ? ORDER BY font
`

type GetLanguageScriptFontsParams struct {
	ScriptName string `json:"script_name"`
	Source     string `json:"source"`
}

func (q *Queries) GetLanguageScriptFonts(ctx context.Context, arg GetLanguageScriptFontsParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLanguageScriptFonts, arg.ScriptName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var font string
		if err := rows.Scan(&font); err != nil {
			return nil, err
		}
		items = append(items, font)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLanguageSpeakers = `-- name: GetLanguageSpeakers :many
SELECT speaker FROM language_typical_speakers WHERE language_name = ? AND source = ? ORDER BY speaker
`

type GetLanguageSpeakersParams struct {
	LanguageName string `json:"language_name"`
	Source       string `json:"source"`
}

func (q *Queries) GetLanguageSpeakers(ctx context.Context, arg GetLanguageSpeakersParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, getLanguageSpeakers, arg.LanguageName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var speaker string
		if err := rows.Scan(&speaker); err != nil {
			return nil, err
		}
		items = append(items, speaker)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertLanguageScriptFont = `-- name: InsertLanguageScriptFont :exec
INSERT INTO language_script_fonts (script_name, source, font)
VALUES (?, ?, ?)
`

type InsertLanguageScriptFontParams struct {
	ScriptName string `json:"script_name"`
	Source     string `json:"source"`
	Font       string `json:"font"`
}

func (q *Queries) InsertLanguageScriptFont(ctx context.Context, arg InsertLanguageScriptFontParams) error {
	_, err := q.db.ExecContext(ctx, insertLanguageScriptFont, arg.ScriptName, arg.Source, arg.Font)
	return err
}

const insertLanguageSpeaker = `-- name: InsertLanguageSpeaker :exec
INSERT INTO language_typical_speakers (language_name, source, speaker)
VALUES (?, ?, ?)
`

type InsertLanguageSpeakerParams struct {
	LanguageName string `json:"language_name"`
	Source       string `json:"source"`
	Speaker      string `json:"speaker"`
}

func (q *Queries) InsertLanguageSpeaker(ctx context.Context, arg InsertLanguageSpeakerParams) error {
	_, err := q.db.ExecContext(ctx, insertLanguageSpeaker, arg.LanguageName, arg.Source, arg.Speaker)
	return err
}

const upsertLanguage = `-- name: UpsertLanguage :exec
INSERT INTO languages (name, source, page, type, script, srd, basic_rules)
VALUES (?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(name, source) DO UPDATE SET
    page = excluded.page,
    type = excluded.type,
    script = excluded.script,
    srd = excluded.srd,
    basic_rules = excluded.basic_rules
`

type UpsertLanguageParams struct {
	Name       string         `json:"name"`
	Source     string         `json:"source"`
	Page       sql.NullInt64  `json:"page"`
	Type       sql.NullString `json:"type"`
	Script     sql.NullString `json:"script"`
	Srd        sql.NullInt64  `json:"srd"`
	BasicRules sql.NullInt64  `json:"basic_rules"`
}

func (q *Queries) UpsertLanguage(ctx context.Context, arg UpsertLanguageParams) error {
	_, err := q.db.ExecContext(ctx, upsertLanguage,
		arg.Name,
		arg.Source,
		arg.Page,
		arg.Type,
		arg.Script,
		arg.Srd,
		arg.BasicRules,
	)
	return err
}

const upsertLanguageScript = `-- name: UpsertLanguageScript :exec
INSERT INTO language_scripts (name, source)
VALUES (?, ?)
ON CONFLICT(name, source) DO NOTHING
`

type UpsertLanguageScriptParams struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

func (q *Queries) UpsertLanguageScript(ctx context.Context, arg UpsertLanguageScriptParams) error {
	_, err := q.db.ExecContext(ctx, upsertLanguageScript, arg.Name, arg.Source)
	return err
}
