// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql"
)

type Spell struct {
	Name                 string         `json:"name"`
	Source               string         `json:"source"`
	Level                sql.NullInt64  `json:"level"`
	School               sql.NullString `json:"school"`
	Page                 sql.NullInt64  `json:"page"`
	Srd                  sql.NullInt64  `json:"srd"`
	SrdName              sql.NullString `json:"srd_name"`
	BasicRules           sql.NullInt64  `json:"basic_rules"`
	Ritual               sql.NullInt64  `json:"ritual"`
	RangeType            sql.NullString `json:"range_type"`
	DistanceType         sql.NullString `json:"distance_type"`
	DistanceAmount       sql.NullInt64  `json:"distance_amount"`
	CompVerbal           sql.NullInt64  `json:"comp_verbal"`
	CompSomatic          sql.NullInt64  `json:"comp_somatic"`
	CompMaterial         sql.NullInt64  `json:"comp_material"`
	CompMaterialText     sql.NullString `json:"comp_material_text"`
	CompMaterialCost     sql.NullInt64  `json:"comp_material_cost"`
	CompMaterialConsumed sql.NullInt64  `json:"comp_material_consumed"`
}

type SpellAltSource struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	Kind      string `json:"kind"`
	Value     string `json:"value"`
}

type SpellCastTime struct {
	SpellName string         `json:"spell_name"`
	Source    string         `json:"source"`
	Ord       int64          `json:"ord"`
	Number    sql.NullInt64  `json:"number"`
	Unit      sql.NullString `json:"unit"`
	Condition sql.NullString `json:"condition"`
}

type SpellDuration struct {
	SpellName     string         `json:"spell_name"`
	Source        string         `json:"source"`
	Ord           int64          `json:"ord"`
	Type          sql.NullString `json:"type"`
	Amount        sql.NullInt64  `json:"amount"`
	TimeUnit      sql.NullString `json:"time_unit"`
	Concentration sql.NullInt64  `json:"concentration"`
}

type SpellDurationEnd struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	Ord       int64  `json:"ord"`
	EndsType  string `json:"ends_type"`
}

type SpellEntry struct {
	SpellName string         `json:"spell_name"`
	Source    string         `json:"source"`
	Section   string         `json:"section"`
	Ord       int64          `json:"ord"`
	BlockType string         `json:"block_type"`
	Heading   sql.NullString `json:"heading"`
	Content   string         `json:"content"`
}

type SpellScalingDice struct {
	SpellName string         `json:"spell_name"`
	Source    string         `json:"source"`
	Label     sql.NullString `json:"label"`
	AtLevel   int64          `json:"at_level"`
	Dice      string         `json:"dice"`
}

type SpellTag struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	TagType   string `json:"tag_type"`
	TagValue  string `json:"tag_value"`
}
