// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	DeleteAltSources(ctx context.Context, arg DeleteAltSourcesParams) error
	DeleteCastTimes(ctx context.Context, arg DeleteCastTimesParams) error
	DeleteDurationEnds(ctx context.Context, arg DeleteDurationEndsParams) error
	DeleteDurations(ctx context.Context, arg DeleteDurationsParams) error
	DeleteEntries(ctx context.Context, arg DeleteEntriesParams) error
	DeleteScalingDice(ctx context.Context, arg DeleteScalingDiceParams) error
	DeleteSpellTags(ctx context.Context, arg DeleteSpellTagsParams) error
	GetSpellsByLevel(ctx context.Context, level sql.NullInt64) ([]GetSpellsByLevelRow, error)
	GetSpellsBySavingThrow(ctx context.Context, tagValue string) ([]GetSpellsBySavingThrowRow, error)
	InsertAltSource(ctx context.Context, arg InsertAltSourceParams) error
	InsertCastTime(ctx context.Context, arg InsertCastTimeParams) error
	InsertDuration(ctx context.Context, arg InsertDurationParams) error
	InsertDurationEnd(ctx context.Context, arg InsertDurationEndParams) error
	InsertEntry(ctx context.Context, arg InsertEntryParams) error
	InsertScalingDice(ctx context.Context, arg InsertScalingDiceParams) error
	InsertSpellTag(ctx context.Context, arg InsertSpellTagParams) error
	UpsertSpell(ctx context.Context, arg UpsertSpellParams) error
}

var _ Querier = (*Queries)(nil)
