// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: spells.sql

package sqlc

import (
	"context"
	"database/sql"
)

const deleteAltSources = `-- name: DeleteAltSources :exec
DELETE FROM
    spell_alt_sources
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteAltSourcesParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteAltSources(ctx context.Context, arg DeleteAltSourcesParams) error {
	_, err := q.db.ExecContext(ctx, deleteAltSources, arg.SpellName, arg.Source)
	return err
}

const deleteCastTimes = `-- name: DeleteCastTimes :exec
DELETE FROM
    spell_cast_time
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteCastTimesParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteCastTimes(ctx context.Context, arg DeleteCastTimesParams) error {
	_, err := q.db.ExecContext(ctx, deleteCastTimes, arg.SpellName, arg.Source)
	return err
}

const deleteDurationEnds = `-- name: DeleteDurationEnds :exec
DELETE FROM
    spell_duration_ends
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteDurationEndsParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteDurationEnds(ctx context.Context, arg DeleteDurationEndsParams) error {
	_, err := q.db.ExecContext(ctx, deleteDurationEnds, arg.SpellName, arg.Source)
	return err
}

const deleteDurations = `-- name: DeleteDurations :exec
DELETE FROM
    spell_duration
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteDurationsParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteDurations(ctx context.Context, arg DeleteDurationsParams) error {
	_, err := q.db.ExecContext(ctx, deleteDurations, arg.SpellName, arg.Source)
	return err
}

const deleteEntries = `-- name: DeleteEntries :exec
DELETE FROM
    spell_entries
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteEntriesParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteEntries(ctx context.Context, arg DeleteEntriesParams) error {
	_, err := q.db.ExecContext(ctx, deleteEntries, arg.SpellName, arg.Source)
	return err
}

const deleteScalingDice = `-- name: DeleteScalingDice :exec
DELETE FROM
    spell_scaling_dice
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteScalingDiceParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteScalingDice(ctx context.Context, arg DeleteScalingDiceParams) error {
	_, err := q.db.ExecContext(ctx, deleteScalingDice, arg.SpellName, arg.Source)
	return err
}

const deleteSpellTags = `-- name: DeleteSpellTags :exec
DELETE FROM
    spell_tags
WHERE
    spell_name = ?
    AND source = ?
`

type DeleteSpellTagsParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) DeleteSpellTags(ctx context.Context, arg DeleteSpellTagsParams) error {
	_, err := q.db.ExecContext(ctx, deleteSpellTags, arg.SpellName, arg.Source)
	return err
}

const getSpell = `-- name: GetSpell :one
SELECT name, source, level, school, page, srd, srd_name, basic_rules, ritual, range_type, distance_type, distance_amount, comp_verbal, comp_somatic, comp_material, comp_material_text, comp_material_cost, comp_material_consumed FROM spells WHERE name = ? AND source = ?
`

type GetSpellParams struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

func (q *Queries) GetSpell(ctx context.Context, arg GetSpellParams) (Spell, error) {
	row := q.db.QueryRowContext(ctx, getSpell, arg.Name, arg.Source)
	var i Spell
	err := row.Scan(
		&i.Name,
		&i.Source,
		&i.Level,
		&i.School,
		&i.Page,
		&i.Srd,
		&i.SrdName,
		&i.BasicRules,
		&i.Ritual,
		&i.RangeType,
		&i.DistanceType,
		&i.DistanceAmount,
		&i.CompVerbal,
		&i.CompSomatic,
		&i.CompMaterial,
		&i.CompMaterialText,
		&i.CompMaterialCost,
		&i.CompMaterialConsumed,
	)
	return i, err
}

const getSpellCastTimes = `-- name: GetSpellCastTimes :many
SELECT spell_name, source, ord, number, unit, condition FROM spell_cast_time WHERE spell_name = ? AND source = ? ORDER BY ord
`

type GetSpellCastTimesParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) GetSpellCastTimes(ctx context.Context, arg GetSpellCastTimesParams) ([]SpellCastTime, error) {
	rows, err := q.db.QueryContext(ctx, getSpellCastTimes, arg.SpellName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellCastTime
	for rows.Next() {
		var i SpellCastTime
		if err := rows.Scan(
			&i.SpellName,
			&i.Source,
			&i.Ord,
			&i.Number,
			&i.Unit,
			&i.Condition,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellDurationEnds = `-- name: GetSpellDurationEnds :many
SELECT spell_name, source, ord, ends_type FROM spell_duration_ends WHERE spell_name = ? AND source = ?
`

type GetSpellDurationEndsParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) GetSpellDurationEnds(ctx context.Context, arg GetSpellDurationEndsParams) ([]SpellDurationEnd, error) {
	rows, err := q.db.QueryContext(ctx, getSpellDurationEnds, arg.SpellName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellDurationEnd
	for rows.Next() {
		var i SpellDurationEnd
		if err := rows.Scan(
			&i.SpellName,
			&i.Source,
			&i.Ord,
			&i.EndsType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellDurations = `-- name: GetSpellDurations :many
SELECT spell_name, source, ord, type, amount, time_unit, concentration FROM spell_duration WHERE spell_name = ? AND source = ? ORDER BY ord
`

type GetSpellDurationsParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) GetSpellDurations(ctx context.Context, arg GetSpellDurationsParams) ([]SpellDuration, error) {
	rows, err := q.db.QueryContext(ctx, getSpellDurations, arg.SpellName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellDuration
	for rows.Next() {
		var i SpellDuration
		if err := rows.Scan(
			&i.SpellName,
			&i.Source,
			&i.Ord,
			&i.Type,
			&i.Amount,
			&i.TimeUnit,
			&i.Concentration,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellEntries = `-- name: GetSpellEntries :many
SELECT spell_name, source, section, ord, block_type, heading, content FROM spell_entries WHERE spell_name = ? AND source = ? ORDER BY section, ord
`

type GetSpellEntriesParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) GetSpellEntries(ctx context.Context, arg GetSpellEntriesParams) ([]SpellEntry, error) {
	rows, err := q.db.QueryContext(ctx, getSpellEntries, arg.SpellName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellEntry
	for rows.Next() {
		var i SpellEntry
		if err := rows.Scan(
			&i.SpellName,
			&i.Source,
			&i.Section,
			&i.Ord,
			&i.BlockType,
			&i.Heading,
			&i.Content,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellScalingDice = `-- name: GetSpellScalingDice :many
SELECT spell_name, source, label, at_level, dice FROM spell_scaling_dice WHERE spell_name = ? AND source = ? ORDER BY at_level, label
`

type GetSpellScalingDiceParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) GetSpellScalingDice(ctx context.Context, arg GetSpellScalingDiceParams) ([]SpellScalingDice, error) {
	rows, err := q.db.QueryContext(ctx, getSpellScalingDice, arg.SpellName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellScalingDice
	for rows.Next() {
		var i SpellScalingDice
		if err := rows.Scan(
			&i.SpellName,
			&i.Source,
			&i.Label,
			&i.AtLevel,
			&i.Dice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellTags = `-- name: GetSpellTags :many
SELECT spell_name, source, tag_type, tag_value FROM spell_tags WHERE spell_name = ? AND source = ? ORDER BY tag_type, tag_value
`

type GetSpellTagsParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
}

func (q *Queries) GetSpellTags(ctx context.Context, arg GetSpellTagsParams) ([]SpellTag, error) {
	rows, err := q.db.QueryContext(ctx, getSpellTags, arg.SpellName, arg.Source)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpellTag
	for rows.Next() {
		var i SpellTag
		if err := rows.Scan(
			&i.SpellName,
			&i.Source,
			&i.TagType,
			&i.TagValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsByLevel = `-- name: GetSpellsByLevel :many
SELECT
    name,
    LEVEL,
    school
FROM
    spells
WHERE
    LEVEL = ?
ORDER BY
    name
`

type GetSpellsByLevelRow struct {
	Name   string         `json:"name"`
	Level  sql.NullInt64  `json:"level"`
	School sql.NullString `json:"school"`
}

func (q *Queries) GetSpellsByLevel(ctx context.Context, level sql.NullInt64) ([]GetSpellsByLevelRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsByLevel, level)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsByLevelRow
	for rows.Next() {
		var i GetSpellsByLevelRow
		if err := rows.Scan(&i.Name, &i.Level, &i.School); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpellsBySavingThrow = `-- name: GetSpellsBySavingThrow :many
SELECT
    s.name,
    s.source
FROM
    spells s
    JOIN spell_tags t ON t.spell_name = s.name
    AND t.source = s.source
WHERE
    t.tag_type = 'savingThrow'
    AND t.tag_value = ?
`

type GetSpellsBySavingThrowRow struct {
	Name   string `json:"name"`
	Source string `json:"source"`
}

func (q *Queries) GetSpellsBySavingThrow(ctx context.Context, tagValue string) ([]GetSpellsBySavingThrowRow, error) {
	rows, err := q.db.QueryContext(ctx, getSpellsBySavingThrow, tagValue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpellsBySavingThrowRow
	for rows.Next() {
		var i GetSpellsBySavingThrowRow
		if err := rows.Scan(&i.Name, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAltSource = `-- name: InsertAltSource :exec
INSERT INTO
    spell_alt_sources (spell_name, source, kind, value)
VALUES
    (?, ?, ?, ?)
`

type InsertAltSourceParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	Kind      string `json:"kind"`
	Value     string `json:"value"`
}

func (q *Queries) InsertAltSource(ctx context.Context, arg InsertAltSourceParams) error {
	_, err := q.db.ExecContext(ctx, insertAltSource,
		arg.SpellName,
		arg.Source,
		arg.Kind,
		arg.Value,
	)
	return err
}

const insertCastTime = `-- name: InsertCastTime :exec
INSERT INTO
    spell_cast_time (spell_name, source, ord, number, unit, condition)
VALUES
    (?, ?, ?, ?, ?, ?)
`

type InsertCastTimeParams struct {
	SpellName string         `json:"spell_name"`
	Source    string         `json:"source"`
	Ord       int64          `json:"ord"`
	Number    sql.NullInt64  `json:"number"`
	Unit      sql.NullString `json:"unit"`
	Condition sql.NullString `json:"condition"`
}

func (q *Queries) InsertCastTime(ctx context.Context, arg InsertCastTimeParams) error {
	_, err := q.db.ExecContext(ctx, insertCastTime,
		arg.SpellName,
		arg.Source,
		arg.Ord,
		arg.Number,
		arg.Unit,
		arg.Condition,
	)
	return err
}

const insertDuration = `-- name: InsertDuration :exec
INSERT INTO
    spell_duration (
        spell_name,
        source,
        ord,
        TYPE,
        amount,
        time_unit,
        concentration
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type InsertDurationParams struct {
	SpellName     string         `json:"spell_name"`
	Source        string         `json:"source"`
	Ord           int64          `json:"ord"`
	Type          sql.NullString `json:"type"`
	Amount        sql.NullInt64  `json:"amount"`
	TimeUnit      sql.NullString `json:"time_unit"`
	Concentration sql.NullInt64  `json:"concentration"`
}

func (q *Queries) InsertDuration(ctx context.Context, arg InsertDurationParams) error {
	_, err := q.db.ExecContext(ctx, insertDuration,
		arg.SpellName,
		arg.Source,
		arg.Ord,
		arg.Type,
		arg.Amount,
		arg.TimeUnit,
		arg.Concentration,
	)
	return err
}

const insertDurationEnd = `-- name: InsertDurationEnd :exec
INSERT INTO
    spell_duration_ends (spell_name, source, ord, ends_type)
VALUES
    (?, ?, ?, ?)
`

type InsertDurationEndParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	Ord       int64  `json:"ord"`
	EndsType  string `json:"ends_type"`
}

func (q *Queries) InsertDurationEnd(ctx context.Context, arg InsertDurationEndParams) error {
	_, err := q.db.ExecContext(ctx, insertDurationEnd,
		arg.SpellName,
		arg.Source,
		arg.Ord,
		arg.EndsType,
	)
	return err
}

const insertEntry = `-- name: InsertEntry :exec
INSERT INTO
    spell_entries (
        spell_name,
        source,
        section,
        ord,
        block_type,
        heading,
        content
    )
VALUES
    (?, ?, ?, ?, ?, ?, ?)
`

type InsertEntryParams struct {
	SpellName string         `json:"spell_name"`
	Source    string         `json:"source"`
	Section   string         `json:"section"`
	Ord       int64          `json:"ord"`
	BlockType string         `json:"block_type"`
	Heading   sql.NullString `json:"heading"`
	Content   string         `json:"content"`
}

func (q *Queries) InsertEntry(ctx context.Context, arg InsertEntryParams) error {
	_, err := q.db.ExecContext(ctx, insertEntry,
		arg.SpellName,
		arg.Source,
		arg.Section,
		arg.Ord,
		arg.BlockType,
		arg.Heading,
		arg.Content,
	)
	return err
}

const insertScalingDice = `-- name: InsertScalingDice :exec
INSERT INTO
    spell_scaling_dice (spell_name, source, label, at_level, dice)
VALUES
    (?, ?, ?, ?, ?)
`

type InsertScalingDiceParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	Label     string `json:"label"`
	AtLevel   int64  `json:"at_level"`
	Dice      string `json:"dice"`
}

func (q *Queries) InsertScalingDice(ctx context.Context, arg InsertScalingDiceParams) error {
	_, err := q.db.ExecContext(ctx, insertScalingDice,
		arg.SpellName,
		arg.Source,
		arg.Label,
		arg.AtLevel,
		arg.Dice,
	)
	return err
}

const insertSpellTag = `-- name: InsertSpellTag :exec
INSERT INTO
    spell_tags (spell_name, source, tag_type, tag_value)
VALUES
    (?, ?, ?, ?)
`

type InsertSpellTagParams struct {
	SpellName string `json:"spell_name"`
	Source    string `json:"source"`
	TagType   string `json:"tag_type"`
	TagValue  string `json:"tag_value"`
}

func (q *Queries) InsertSpellTag(ctx context.Context, arg InsertSpellTagParams) error {
	_, err := q.db.ExecContext(ctx, insertSpellTag,
		arg.SpellName,
		arg.Source,
		arg.TagType,
		arg.TagValue,
	)
	return err
}

const upsertSpell = `-- name: UpsertSpell :exec
INSERT INTO
    spells (
        name,
        source,
        LEVEL,
        school,
        PAGE,
        srd,
        srd_name,
        basic_rules,
        ritual,
        range_type,
        distance_type,
        distance_amount,
        comp_verbal,
        comp_somatic,
        comp_material,
        comp_material_text,
        comp_material_cost,
        comp_material_consumed
    )
VALUES
    (
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?,
        ?
    ) ON CONFLICT(name, source) DO
UPDATE
SET
    LEVEL = excluded.level,
    school = excluded.school,
    PAGE = excluded.page,
    srd = excluded.srd,
    srd_name = excluded.srd_name,
    basic_rules = excluded.basic_rules,
    ritual = excluded.ritual,
    range_type = excluded.range_type,
    distance_type = excluded.distance_type,
    distance_amount = excluded.distance_amount,
    comp_verbal = excluded.comp_verbal,
    comp_somatic = excluded.comp_somatic,
    comp_material = excluded.comp_material,
    comp_material_text = excluded.comp_material_text,
    comp_material_cost = excluded.comp_material_cost,
    comp_material_consumed = excluded.comp_material_consumed
`

type UpsertSpellParams struct {
	Name                 string         `json:"name"`
	Source               string         `json:"source"`
	Level                sql.NullInt64  `json:"level"`
	School               sql.NullString `json:"school"`
	Page                 sql.NullInt64  `json:"page"`
	Srd                  sql.NullInt64  `json:"srd"`
	SrdName              sql.NullString `json:"srd_name"`
	BasicRules           sql.NullInt64  `json:"basic_rules"`
	Ritual               sql.NullInt64  `json:"ritual"`
	RangeType            sql.NullString `json:"range_type"`
	DistanceType         sql.NullString `json:"distance_type"`
	DistanceAmount       sql.NullInt64  `json:"distance_amount"`
	CompVerbal           sql.NullInt64  `json:"comp_verbal"`
	CompSomatic          sql.NullInt64  `json:"comp_somatic"`
	CompMaterial         sql.NullInt64  `json:"comp_material"`
	CompMaterialText     sql.NullString `json:"comp_material_text"`
	CompMaterialCost     sql.NullInt64  `json:"comp_material_cost"`
	CompMaterialConsumed sql.NullInt64  `json:"comp_material_consumed"`
}

func (q *Queries) UpsertSpell(ctx context.Context, arg UpsertSpellParams) error {
	_, err := q.db.ExecContext(ctx, upsertSpell,
		arg.Name,
		arg.Source,
		arg.Level,
		arg.School,
		arg.Page,
		arg.Srd,
		arg.SrdName,
		arg.BasicRules,
		arg.Ritual,
		arg.RangeType,
		arg.DistanceType,
		arg.DistanceAmount,
		arg.CompVerbal,
		arg.CompSomatic,
		arg.CompMaterial,
		arg.CompMaterialText,
		arg.CompMaterialCost,
		arg.CompMaterialConsumed,
	)
	return err
}
